name: Deploy Shiny app

on:
  push:
    branches: [ "main" ]   # change this if you deploy from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install rsconnect
        run: R -q -e 'install.packages("rsconnect", repos="https://cloud.r-project.org")'

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          R -q -e 'rsconnect::setAccountInfo(Sys.getenv("SHINYAPPS_ACCOUNT"),
                                              Sys.getenv("SHINYAPPS_TOKEN"),
                                              Sys.getenv("SHINYAPPS_SECRET"))'
          R -q -e 'rsconnect::deployApp(appDir=".", forceUpdate=TRUE)'
